version: 2.1

jobs:
  build:
    docker:
      - image: cimg/deploy:2023.08-node
        environment:
          DATABASE_URL: postgres://steam_clone_fec_user:mK3Q1M96eV11yc0yAfXxqibkjZzaBmxp@dpg-citeehh5rnuhcntjlc90-a.oregon-postgres.render.com/steam_clone_fec?ssl=true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
  test:
    docker:
      - image: cimg/deploy:2023.08-node
    steps:
      - run:
          name: Test Code
          command: npm run test

  deploy:
    docker:
      - image: cimg/deploy:2023.08-node
    steps:
      - run:
          name: Deploy API to Render
          command: |
            const fetch = require('node-fetch');
            const deployUri = process.env.DEPLOY_URI;

            fetch(deployUri)
              .then((response) => {
                if (response.status === 200) {
                  console.log('Deployment successful!');
                } else {
                  console.error('Deployment failed with response code:', response.status);
                  response.text().then((text) => console.error(text));
                  process.exit(1);
                }
              })
              .catch((error) => {
                console.error('Error during deployment:', error.message);
                process.exit(1);
              });

workflows:
  build_test_deploy:
    jobs:
      - build
      - test
      - deploy
