version: 2.1
setup: true

#sequential workflow, where build, test, and deploy run only if their precedecessor finishes
workflows:
  build_test_deploy:
    jobs:
      docker:
        - image: cimg/deploy:2023.08-node

jobs:
  build_and_test:
    executor:
      docker: cimg/deploy:2023.08-node
    steps:
      - checkout             
      - run: node --version
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Build server
          command: npm run build
      - run:
          name: Start server
          command: npm run deploy
          background: true

    deploy:
      docker:
        - image: cimg/deploy:2023.08-node
      steps:
        requires: 
          - build_and_test
        - run:
            name: Deploy API to Render
            command: |
              const fetch = require('node-fetch');
              const deployUri = process.env.DEPLOY_URI;

              fetch(deployUri)
                .then((response) => {
                  if (response.status === 200) {
                    console.log('Deployment successful!');
                  } else {
                    console.error('Deployment failed with response code:', response.status);
                    response.text().then((text) => console.error(text));
                    process.exit(1);
                  }
                })
                .catch((error) => {
                  console.error('Error during deployment:', error.message);
                  process.exit(1);
                });





